# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 1889e9a70b245108c8a554023946d57cbc4553dd

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

jpa:
    show_sql: true
    
mail:
    host: smtp.gmail.com
    port: 587
    username: petcaresiberian@gmail.com
    password: Siberian!
    protocol: smtp
    tls: true
    auth: true
    from: petcaresiberian@gmail.com

authentication:
    xauth:
        secret: myXAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

swagger:
    title: petcare API
    description: petcare applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
